<script lang="ts">
  import { base } from '$app/paths';
</script>

<svelte:head>
  <title>Terms and Conditions | AxelBase</title>
  <meta name="description" content="View the Terms and Conditions for using the AxelBase Capacity Converter utility." />
</svelte:head>

<div class="container fade-in post-layout">
<div class="breadcrumbs-wrapper">
  <nav class="breadcrumbs" aria-label="Breadcrumb">
    <a href="{base}/" class="home-icon" title="Home">
      <i class="bi bi-house-door-fill"></i>
    </a>

    <span class="separator">
      <i class="bi bi-chevron-right"></i>
    </span>

    <span class="current-page">
      Terms and Conditions
    </span>
  </nav>
</div>

<style>
  .breadcrumbs-wrapper {
    margin-bottom: 2.5rem;
  }

  .breadcrumbs {
    display: inline-flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.6rem 1.2rem;
    background: var(--glass-bg);
    backdrop-filter: blur(10px);
    border: 1px solid var(--glass-border);
    border-radius: 50px;
    font-size: 0.85rem;
    font-weight: 600;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.03);
  }

  /* Icons and Links */
  .home-icon {
    color: var(--brand-orange);
    display: flex;
    align-items: center;
    transition: transform 0.2s ease;
    text-decoration: none;
  }

  .home-icon:hover {
    transform: scale(1.1);
  }

  .breadcrumb-link {
    color: var(--color-text-main);
    text-decoration: none;
    opacity: 0.7;
    transition: all 0.2s ease;
  }

  .breadcrumb-link:hover {
    opacity: 1;
    color: var(--brand-orange);
  }

  /* Separator Styling */
  .separator {
    display: flex;
    align-items: center;
    color: var(--brand-orange);
    font-size: 0.7rem;
    opacity: 0.5;
  }

  /* Current Page Text */
  .current-page {
    color: var(--color-text-main);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 250px; /* Prevents mobile explosion */
    opacity: 0.9;
  }

  @media (max-width: 576px) {
    .current-page {
      max-width: 120px;
    }
    .breadcrumbs {
      padding: 0.5rem 1rem;
    }
  }

  /* Integration with your existing prose */
  .post-layout {
    max-width: 800px;
    padding: 2rem 1rem 4rem 1rem;
    margin: 0 auto;
  }

  .prose h1 {
    font-size: 2.5rem;
    margin-bottom: 0.5rem;
    color: var(--color-text-main);
    font-family: 'Poppins', sans-serif;
  }
</style>

  <article class="prose">
    <h1>Terms and Conditions</h1>
    <p class="post-meta">Last Updated: March 10, 2026</p>

    <h2>1. Acceptance of Terms</h2>
    <p>By accessing and using the <strong>AxelBase Capacity Converter</strong>, you agree to be bound by these Terms and Conditions. This is a <em>legal agreement</em> between you and AxelBase. If you do not agree with any part of these terms, you are prohibited from using this utility. These terms apply to all visitors, users, and others who wish to access the service.</p>

    <h2>2. Description of Service</h2>
    <p>AxelBase provides a web-based interface for converting various capacity and volume units (e.g., Liters, Gallons, Milliliters). The service is provided <strong>"as-is"</strong> and <strong>"as-available."</strong> While we strive for 100% mathematical accuracy, the tool is intended for <em>educational and general informational purposes</em> only. It should not be the sole basis for high-stakes industrial, medical, or scientific decisions where life or property is at risk.</p>

    <h2>3. Intellectual Property</h2>
    <p>The code, design, <strong>Pearl Orange</strong> theme, branding, and original content within this tool are the exclusive property of <strong>AxelBase</strong>. You may use the tool for personal or commercial projects; however, you may not <strong>scrape</strong>, <strong>replicate</strong>, or <strong>redistribute</strong> the underlying source code without express written permission. You are granted a limited, non-exclusive license to use the results generated by the converter for your own needs.</p>

    <h2>4. User Responsibilities</h2>
    <p>As a user, you agree not to attempt to interfere with the <em>integrity or performance</em> of the website. Since the tool operates client-side, you are responsible for ensuring that your browser environment is secure. You agree not to use the tool for any <strong>illegal or unauthorized purpose</strong>. AxelBase reserves the right to terminate access to the tool if these terms are violated.</p>

    <h2>5. Limitation of Liability</h2>
    <p>To the maximum extent permitted by law, <strong>AxelBase</strong> and its developers shall not be liable for any <em>indirect, incidental, special, or consequential damages</em> arising out of your use of the tool. This includes, but is not limited to, errors in conversion results, loss of data, or financial loss resulting from reliance on the tool. You use this converter at <strong>your own risk</strong>.</p>

    <h2>6. Disclaimer of Warranty</h2>
    <p>We provide no warranties, either <strong>express or implied</strong>, regarding the accuracy or reliability of the conversion algorithms. While we use standard mathematical constants (e.g., 1 Gallon = 3.78541 Liters), rounding differences may occur. <em>Users are encouraged to verify critical measurements</em> through secondary sources.</p>

    <h2>7. Governing Law</h2>
    <p>These terms shall be governed and construed in accordance with the laws of our operating jurisdiction, without regard to its conflict of law provisions. Any failure to enforce a right or provision of these terms will not be considered a waiver of those rights.</p>

    <p class="italic-note">By using AxelBase, you acknowledge that you have read and understood these terms. We thank you for choosing our tools to power your projects.</p>
  </article>
</div>

<style>
  /* Styles are identical to Privacy Policy for consistency */
  .post-layout { max-width: 800px; padding-top: 5rem; padding-bottom: 4rem; }
  .breadcrumbs { display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1.5rem; font-size: 0.9rem; opacity: 0.7; }
  .breadcrumbs a { color: var(--brand-orange); text-decoration: none; }
  .prose { line-height: 1.8; color: var(--color-text-main); }
  .prose .post-meta { font-size: 0.9rem; margin-bottom: 2rem; border-bottom: 1px solid var(--glass-border); padding-bottom: 1rem; opacity: 0.6; }
  .prose h1, .prose h2 { color: var(--brand-orange); font-weight: 700; }
  .prose h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
  .prose h2 { margin-top: 2.5rem; border-bottom: 1px solid var(--glass-border); padding-bottom: 0.5rem; }
  .prose .italic-note { font-style: italic; opacity: 0.7; text-align: center; margin-top: 3rem; }
</style>